"""Initial migration.

Revision ID: 664d4bf67baa
Revises: 
Create Date: 2022-10-27 21:02:56.382119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664d4bf67baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'email')
    # ### end Alembic commands ###
